version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
    ports:
      - '3050:80'
    # command: ["nginx", "-c", "/etc/nginx/conf.d/default.conf", "-t"]
    restart: always
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGDATABASE=postgres
      - PGHOST=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - PGUSER=postgres
    volumes:
      - /app/node_modules
      - ./server:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app